language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  - ./travis.sh

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar

notifications:
  email: false
  on_start: always
  webhooks:
    - secure: "As5j3h47958MFaj3BkGi81M8f2n7eh27Eu/y/zkO9T94SCuqUUKbgR5FV9P7kdidL2KxgwQB4NC/YiYtDCfTAOKS//u6BQRSw7IvXxBScAFCvDfpmgYdnai6DBboYsCi5nPUXGccojJcbXKbiToYuhz8Yw77+0IyxGI0inLMBVc="

addons:
  apt:
    packages:
      # upgrade java 8 as the default version 1.8.0_31 prevents from compiling sources
      # https://github.com/travis-ci/travis-ci/issues/4042
      - oracle-java8-installer
